
[general]
import = ["./dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 0.95
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "LBracket"
mods = "Alt"
command = { program = "sh", args = ["-c", "~/.config/alacritty/change_opacity.sh -0.05"] }

[[keyboard.bindings]]
key = "RBracket"
mods = "Alt"
command = { program = "sh", args = ["-c", "~/.config/alacritty/change_opacity.sh 0.05"] }

