$ANSIBLE_VAULT;1.1;AES256
30356164666661626233653438303833653566316464373636356565633833303163393038663137
3166636231636630366339656633313435356530663735300a643037343464363437303465653638
35376662613632656266616162346564636264363361323030643037373936613039336465333065
3438633833626632390a646466613165366134643331343539656261623761363933333962386335
35656336343235646662346535633432666365613866646238323064386464633861356136653935
32346262663262353561656231343439613933356339393464363634313366666265313566313937
38343235633532666633323930373163636233656566616166313666636138623235663764303832
61616533316632313638343132386638626464613265363034663761643833626266313265316434
36313164396262393965393662356131346536653737646633303839616135663833306539633965
39663532313238643762346535393466393036623132386563646238386430346562373161393439
61386230626661613539356638366338656234313931333462656462376366616263636466356430
30313930313537373835626365623563333261326538626436386338366237383465366133323534
63656565393662623562326562646135373162336135333665643664653333373662
