$ANSIBLE_VAULT;1.1;AES256
66663463653931323636653039643337613437303161623564623835313039663963663636386635
6562333538323732663634656361373464316463373763610a306434616164386636353535373666
30616231613331653739636537346338613061373430393531646265343734666238386238393765
3138643435326233630a326334356330373933346564333530323831386663383635616564366261
31626334623735666632666532346533653464373161303264633833343731373430643830653433
32316662326439626261313962646639313064656534363462623439353762633462626264323563
61643637643936363065363638396539353532356637613261626662376365623732666163353335
62396238303135333334
