$ANSIBLE_VAULT;1.1;AES256
62396236616236663631646339346531356538383166613663663966353237653535353266626333
3436313934373234663761626130623037316566353664390a663466616534313536393337663233
34386565663336336439633132373135616631393034643266323438616335633465626237666338
3932633035636633630a346562663366643739373266633932303134386337323630346433396661
66376433636266336563333336366661373861383763666134666165393639326365323033303566
34646438646539303234306537613433323266383533353365356265353333613561366232663465
61316334653262323863663139366162303133323731356362323639633862666632626363663061
66363337656463353761363566656461313831383631303230313165386132323130646130313633
64626466363337353663636462353863626139303531656535333037346431303465373338643035
61643033636330306666646362613063313062643262613164346438646236613061643762623836
33303964383632303334623034396262623063306665303834626330383763353463653431663030
31616663323332303438333665376165363033373430366561393864643730383132366338306636
63343938356539373931303336323430666330666334353166336235333461653734
