$ANSIBLE_VAULT;1.1;AES256
38353034643736613437613565303235396566323562666435393137643838383738623232323163
6666633962613162616561303061643264323635383961310a353734346439366334346338613363
36383063653965323061353435323136383061383866623433376531303063363432393237343563
6538303965313231340a346633363535323734393230356135356334656332646566666566366137
38653664363363626432383630303933646632313531393661636664303162303535633036346635
3962353166396234653135663832343664633631643731326333
