---
- name: Создание директории для конфигурации SDDM
  become: true
  ansible.builtin.file:
    path: /etc/sddm.conf.d
    state: directory
    mode: '0755'

- name: Настройка SDDM (autologin, hidpi)
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/sddm.conf.d/{{ item }}"
    mode: '0644'
  loop:
    - autologin.conf
    - hidpi.conf

- name: Включение службы SDDM
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: yes

- name: Включение таймера очистки кэша пакетов (paccache)
  become: true
  ansible.builtin.systemd:
    name: paccache.timer
    enabled: yes
    state: started

- name: Установка глобальных NPM пакетов
  become: true
  community.general.npm:
    name: "@google/gemini-cli"
    global: yes
    state: present

- name: Создание директории systemd user
  become: false
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Копирование пользовательских systemd сервисов
  become: false
  ansible.builtin.copy:
    src: "systemd/{{ item }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/systemd/user/{{ item }}"
    mode: '0644'
  loop:
    - check-updates.service
    - check-updates.timer
    - check-weather.service
    - check-weather.timer
    - update-dracula-icons.service
    - update-dracula-icons.timer

- name: Активация systemd таймеров
  become: false
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
  loop:
    - check-updates.timer
    - check-weather.timer
    - gammastep.service
    # - update-dracula-icons.timer # Пока не включаем, чтобы не спамить
