---
system_packages:
  # Base & System
  - base
  - base-devel
  - linux
  - linux-firmware
  - intel-ucode
  - networkmanager
  - iwd
  - bluez
  - bluez-utils
  - pacman-contrib
  - git
  - which
  - wget
  - curl
  - zip
  - unzip
  - 7zip
  - unrar

  # UI & Window Manager
  - hyprland
  - hyprpaper
  - hypridle
  - hyprlock
  - waybar
  - dunst
  - wofi
  - nwg-look
  - nwg-displays
  - qt5-wayland
  - qt6-wayland
  - gammastep
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gnome

  # Terminal & Shell
  - kitty
  - alacritty
  - fish
  - starship
  - zoxide
  - fzf
  - eza
  - bat
  - tmux
  - screen
  - aerc

  # Editors & Dev
  - vim
  - nano
  - go
  - rust
  - cargo
  - npm
  - python-pip
  - python-pipenv
  - python-pipx
  - uv
  - cmake
  - ninja
  - gettext
  - meson
  - rust
  - cargo
  - clang
  - gperf
  - direnv
  - pre-commit

  # Tools
  - yazi
  - jq
  - fd
  - ripgrep
  - btop
  - htop
  - dust
  - duf
  - tldr
  - tree
  - chafa
  - wl-clipboard
  - brightnessctl
  - pavucontrol
  - libpulse
  - less
  - w3m
  - translate-shell

  # Apps
  - firefox
  - chromium
  - obsidian
  - telegram-desktop
  - qbittorrent
  - bitwarden

  # Security
  - pass
  - gnupg
  - bitwarden-cli

  # Fonts
  - ttf-jetbrains-mono-nerd
  - otf-font-awesome
  - noto-fonts-emoji

aur_packages:
  - checkupdates-systemd-git
  - swww
  - dracula-gtk-theme
  - dracula-icons-git
  - xcursor-obsidian
